package com.serge.medlife.screens.navigation

sealed class NavRoute(val path: String) {
    object Splash : NavRoute("splash")
    object AuthSplash : NavRoute("authSplash")
    object Register : NavRoute("register_screen")
    object Login : NavRoute("login")
    object Main : NavRoute("main")

    object DoctorMain: NavRoute("doctorMain")
    object Services : NavRoute("services")
    object ServicesNew: NavRoute("newServices")
    object Walkthrough: NavRoute("Walkthrough")
    object History: NavRoute("history")
    object Profile: NavRoute("profile")
    object ChatDoc: NavRoute("chatDoc") {
        fun createRoute(category: String) = "chatDoc/$category"
    }
    object Chat: NavRoute("chat")
    object DocDtls: NavRoute("docDtls?name={name}&specialization={specialization}&gender={gender}")
    object Appointment: NavRoute("appointment/{doctorName}/{doctorSpecialization}/{doctorGender}/{date}/{hours}")
    object appointmentSuccess: NavRoute("appointmentSuccess")
    object Notifications: NavRoute("notifications")
    object Cart: NavRoute("cart")
    object findingPharma: NavRoute("findPharma")
    object emptyCart: NavRoute("emptyCart")
    object HealthShop: NavRoute("shop")
    object medGrid: NavRoute("medGrid")
    object medDesc: NavRoute("medDesc")
    object hospital: NavRoute("hospital")
    object hospiDtls: NavRoute("hospiDtls")
    object newHospitalMap: NavRoute("googleMap")
    object hospiMap: NavRoute("hospiMap")
    object medReminder: NavRoute("medReminder")
    object addMed: NavRoute("addMed")
    object savedReminder: NavRoute("savedReminder")
    object specialist: NavRoute("specialist")
    object articleHome: NavRoute("articleHome")
    object articleRead: NavRoute("articleRead")
    object articleGrid: NavRoute("articleGrid")
    object presHist: NavRoute("presHist")
    object healthHist: NavRoute("healthHist")
    object transactions: NavRoute("transactions")
    object accSett: NavRoute("accSett")
    object clearNoti: NavRoute("clearNoti")
    object doctorRegisterConfirmation: NavRoute("doctorRegisterConfirmation")
}