package com.example.medcare.screens.navigation

sealed class NavRoute(val path: String) {
    object Splash : com.example.medcare.screens.navigation.NavRoute("splash")
    object AuthSplash : com.example.medcare.screens.navigation.NavRoute("authSplash")
    object Register : com.example.medcare.screens.navigation.NavRoute("register_screen")
    object Login : com.example.medcare.screens.navigation.NavRoute("login")
    object OTP : com.example.medcare.screens.navigation.NavRoute("otp")
    object Verification : com.example.medcare.screens.navigation.NavRoute("verification")
    object Main : com.example.medcare.screens.navigation.NavRoute("main")

    object DoctorMain: com.example.medcare.screens.navigation.NavRoute("doctorMain")
    object Services : com.example.medcare.screens.navigation.NavRoute("services")
    object OnBoard : com.example.medcare.screens.navigation.NavRoute("onBoard")
    object Walkthrough: com.example.medcare.screens.navigation.NavRoute("walkthrough")
    object History: com.example.medcare.screens.navigation.NavRoute("history")
    object Profile: com.example.medcare.screens.navigation.NavRoute("profile")
    object ChatDoc: com.example.medcare.screens.navigation.NavRoute("chatDoc")
    object DocDtls: com.example.medcare.screens.navigation.NavRoute("docDtls")
    object Appointment: com.example.medcare.screens.navigation.NavRoute("appointment/{date}/{hours}")
    object appointmentSuccess: com.example.medcare.screens.navigation.NavRoute("appointmentSuccess")
    object Notifications: com.example.medcare.screens.navigation.NavRoute("notifications")
    object Cart: com.example.medcare.screens.navigation.NavRoute("cart")
    object findingPharma: com.example.medcare.screens.navigation.NavRoute("findPharma")
    object emptyCart: com.example.medcare.screens.navigation.NavRoute("emptyCart")
    object HealthShop: com.example.medcare.screens.navigation.NavRoute("shop")
    object medGrid: com.example.medcare.screens.navigation.NavRoute("medGrid")
    object medDesc: com.example.medcare.screens.navigation.NavRoute("medDesc")
    object hospital: com.example.medcare.screens.navigation.NavRoute("hospital")
    object hospiDtls: com.example.medcare.screens.navigation.NavRoute("hospiDtls")
    object hospiLayout: com.example.medcare.screens.navigation.NavRoute("hospiLayout")
    object hospiMap: com.example.medcare.screens.navigation.NavRoute("hospiMap")
    object medReminder: com.example.medcare.screens.navigation.NavRoute("medReminder")
    object addMed: com.example.medcare.screens.navigation.NavRoute("addMed")
    object savedReminder: com.example.medcare.screens.navigation.NavRoute("savedReminder/{medName}/{dosage}/{timings}")
    object specialist: com.example.medcare.screens.navigation.NavRoute("specialist")
    object articleHome: com.example.medcare.screens.navigation.NavRoute("articleHome")
    object articleRead: com.example.medcare.screens.navigation.NavRoute("articleRead")
    object articleGrid: com.example.medcare.screens.navigation.NavRoute("articleGrid")
    object presHist: com.example.medcare.screens.navigation.NavRoute("presHist")
    object healthHist: com.example.medcare.screens.navigation.NavRoute("healthHist")
    object transactions: com.example.medcare.screens.navigation.NavRoute("transactions")
    object accSett: com.example.medcare.screens.navigation.NavRoute("accSett")
    object clearNoti: com.example.medcare.screens.navigation.NavRoute("clearNoti")
    object pharmaPortal: com.example.medcare.screens.navigation.NavRoute("pharmaPortal")
    object pharmaRegister: com.example.medcare.screens.navigation.NavRoute("pharmaRegister")
    object doctorRegisterConfirmation: com.example.medcare.screens.navigation.NavRoute("doctorRegisterConfirmation")
}